import '@/app/globals.css'

export const metadata = {
  title: 'Nija Dashboard',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`UI-Ecommerce`}>{children}</body>
    </html>
  )
}
