import '@/app/globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'

import { Sidebar, Topbar } from '@/components/organisms'

const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Nija Dashboard',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`UI-Ecommerce`}>
        <div className='fixed left-0 top-0 z-50 w-[280px]'>
          <Sidebar />
        </div>

        <div className='fixed inset-0 z-50 ml-[280px]'>
          <Topbar />
        </div>

        <main className='relative min-h-screen bg-netral-20/50 pt-20'>
          {children}
        </main>
      </body>
    </html>
  )
}
