import "@/app/globals.css"
import { Plus_Jakarta_Sans } from "next/font/google"

import { Sidebar, Topbar } from "@/components/organisms"

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] })

export const metadata = {
  title: "Nija Dashboard",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`UI-Ecommerce`}>
        <div className='fixed left-0 top-0 z-10 w-64 2xl:w-72'>
          <Sidebar />
        </div>

        <div className='fixed inset-0 z-10 ml-64 h-20 w-[calc(100vw_-_280px)] 2xl:ml-72'>
          <Topbar />
        </div>

        <main className='relative z-0 min-h-screen bg-netral-20/50 pl-64 pt-20 2xl:pl-72'>
          {children}
        </main>
      </body>
    </html>
  )
}
